ALTER TABLE "Cv"
ADD COLUMN IF NOT EXISTS "contextText" TEXT;

DROP TABLE IF EXISTS "Certificate";
DROP TABLE IF EXISTS "AdditionalText";
DROP TABLE IF EXISTS "CvMeta";

DROP INDEX IF EXISTS "User_publicSlug_key";

ALTER TABLE "User"
DROP COLUMN IF EXISTS "publicSlug";
